apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g0wy69be5-python
  janus-idp.io/tekton: g0wy69be5-python
  backstage.io/kubernetes-id: g0wy69be5-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: g0wy69be5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
